config/routes.rb
Rails.application.routes.draw do
  resources :articles
  get 'analytics/index'
  root 'articles#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/analytic.rb
class Analytic < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: { minimum: 5 }
    validates :content, presence: true, length: { minimum: 10 }
end

app/models/search.rb
class Search < ApplicationRecord
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  def index   
    ignore_list = ['what', 'the', 'is', 'a', 'to', 'of', 'and', 'in', 'for', 'on', 'that', 'by', 'this', 'with', 'i', 'who', 'how']
    question_list = ['what', 'who', 'how', 'when', 'where', 'which', 'why']

    @analytics = Analytic.all.order(count: :desc).reject do |analytic|
      ignore_list.include?(analytic.word)
    end

    @questions = Analytic.all.order(count: :desc).select do |analytic|
      question_list.include?(analytic.word)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :turbo_frame_request_variant

    private

    def turbo_frame_request_variant
        request.variant = :turbo_frame if turbo_frame_request?
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    if params[:query].present?
      # Search for articles with title that contains the params[:query] and save it to @articles variable.
      @articles = Article.where("title LIKE ?", "%#{params[:query]}%")
      # Remove all non-alphanumeric characters from the params[:query] and save it to query variable.
      query = params[:query].gsub!(/[^0-9A-Za-z]/, ' ')      
      # Split the query variable into an array of words.
      query.split.each do |word|
        if word.length > 2
          if Analytic.find_by(word: word)
            Analytic.find_by(word: word).increment!(:count)
          else
            Analytic.create(word: word, count: 1)
          end
        end          
      end
      # Save the params[:query] to input field of seaches table.
      Search.create(input: query)
    else
      @articles = Article.all
    end
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content)
    end

end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/analytics/index.html.erb
<h1>Ranking of searches by words</h1>

<div class="row">
  <div class="col-md-9 col-12">
    <table class="table table-bordered">
      <tr>
        <th>Word</th>
        <th>Typed number</th>
      </tr>
        <% @analytics.each do |a| %>
        <tr>
          <td><%= a.word %></td>
          <td><%= a.count %></td>
        </tr>
      <% end %>
    </table>
  </div>

  
  <div class="col-md-3 col-12">
    <table class="table table-bordered">
      <tr>
        <th>Trending</th>
      </tr>
      <% @analytics.first(3).each do |search| %>
        <tr>
          <td><strong><%= search.word %></strong></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>
<div class='row'>
<h3>Most used question world</h3>
    <table class="table table-bordered">
      <tr>
        <th>Question word</th>
        <th>Asked time</th>
      </tr>
        <% @questions.each do |a| %>
        <tr>
          <td><%= a.word %></td>
          <td><%= a.count %></td>
        </tr>
      <% end %>
    </table>
</div>

<%= link_to "Back to search page", root_path %>

<p>Next time we will post here how users formulate their search</p>

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <%= article.title %> <%= link_to "View", article_path(article) %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= article.content %>
  </p>

</div>

app/views/articles/_articles.html.erb
<%= turbo_frame_tag "articles" do %>
  <%= render articles %>
<% end %>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html+turbo_frame.erb
<%= turbo_frame_tag "articles" do %>
  <%= render @articles %>
<% end %>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>
<%= form_with(url: articles_path, method: "GET", data: { controller: "form-submission", turbo_frame: "articles", turbo_action: "advance" }) do |form| %>
  <%= form.label :query, "Search by title:" %>
  <%= form.text_field :query, data: { action: "input->form-submission#search" } %>
  <%= form.submit "Search", name: nil %>
<% end %>
<!-- Rendering the new partial here -->
<%= render "articles", articles: @articles %>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealtimeSearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
      <%= link_to "Search Engine", articles_path, class: "navbar-brand" %> 
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Search", articles_path, class: "nav-link" %>                                    
          </li>
          <li class="nav-item">
             <%= link_to "View Analytics", analytics_index_path, class: "nav-link" %>  
          </li>
        </ul>
      </div>
      </div>
    </nav>

  <body>
    <div class="container justify-content-center text-center ">
      <%= yield %>
    </div>
  </body>
</html>